### ISSUE TITLE
Windows installation errors

### ISSUE THREAD

**Issue by spizeck** [kassuro/fcc_progress_checker#1]
So I am pretty new to all this. When I tried to install the cairosvg and lxml I got pip install errors. Seems the dependencies for these are linux exclusive (I am probably wrong and just haven't found a way to install them in windows yet) but thought I would let you know about the error and if you have a workaround, I would suggest putting it in the README.

**Comment by kassuro** [comment]
Maybe there are missing some library headers, I will test this later on a windows machine and see what can be done about this. Thanks for opening that issue.
